import type { DocumentAnalysis } from './schemas/document';
import type { SituationAnalysis } from './schemas/situation';
import type { Comparison } from './schemas/comparison';

export const STATUTORY_DISCLAIMER_HEADER = `══════════════════════════════════════════════════════════════════════════
GAVEL LEGAL INTELLIGENCE REPORT
Generated: ${new Date().toISOString()}
CONFIDENTIAL & PRIVILEGED PREPARATION MATERIAL
══════════════════════════════════════════════════════════════════════════
DISCLAIMER & REGULATORY NOTICE:
This report is generated by Gavel for informational, educational, and
consultation preparation purposes only. Gavel is an artificial intelligence
system and is NOT a law firm, advocate, or licensed legal practitioner.
Nothing in this document constitutes legal advice, legal opinion, or an
attorney-client relationship. Statutory guidance complies with the Advocates Act, 1961.
Always consult a licensed attorney or advocate for legal matters.
══════════════════════════════════════════════════════════════════════════`;

export function sanitizeFilename(name: string): string {
  const sanitized = name
    .replace(/\.\./g, '')
    .replace(/[^a-zA-Z0-9._-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^[.-]+|[.-]+$/g, '');
  return sanitized.slice(0, 60) || 'dossier';
}

export function downloadFile(content: string, filename: string, mimeType: string): void {
  if (typeof window === 'undefined') return;
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = sanitizeFilename(filename);
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  if (typeof window === 'undefined') return false;
  try {
    if (navigator?.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {
    // Fall back to execCommand
  }

  try {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-9999px';
    textArea.style.top = '-9999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    const successful = document.execCommand('copy');
    document.body.removeChild(textArea);
    return successful;
  } catch {
    return false;
  }
}

// ==========================================
// Mode 1: Document Decoder Formatters
// ==========================================

export function formatDocumentMarkdown(data: DocumentAnalysis, fileName?: string): string {
  const sections: string[] = [STATUTORY_DISCLAIMER_HEADER, ''];

  sections.push(`# Document Analysis Report: ${data.documentType}`);
  if (fileName) sections.push(`**Original File:** ${fileName}`);
  sections.push(`**Identified Parties:** ${data.parties?.join(', ') || 'Not specified'}`);
  sections.push('');

  sections.push('## Executive Summary');
  sections.push(data.summary);
  sections.push('');

  sections.push('## Risk Scorecard');
  const highRisks = data.clauses.filter((c) => c.risk === 'high');
  const cautionRisks = data.clauses.filter((c) => c.risk === 'caution');
  const standardRisks = data.clauses.filter((c) => c.risk === 'standard');

  sections.push(`### 🔴 High Risk Clauses (${highRisks.length})`);
  if (highRisks.length === 0) {
    sections.push('_No high risk clauses identified._');
  } else {
    for (const c of highRisks) {
      sections.push(`#### ${c.title} (Obligation: ${c.obligation})`);
      sections.push(`**Why High Risk:** ${c.riskReason}`);
      sections.push(`**Plain-English Meaning:** ${c.simplified}`);
      sections.push('```');
      sections.push(c.originalText);
      sections.push('```');
      sections.push('');
    }
  }

  sections.push(`### 🟡 Caution Clauses (${cautionRisks.length})`);
  if (cautionRisks.length === 0) {
    sections.push('_No caution clauses identified._');
  } else {
    for (const c of cautionRisks) {
      sections.push(`#### ${c.title} (Obligation: ${c.obligation})`);
      sections.push(`**Why Caution:** ${c.riskReason}`);
      sections.push(`**Plain-English Meaning:** ${c.simplified}`);
      sections.push('```');
      sections.push(c.originalText);
      sections.push('```');
      sections.push('');
    }
  }

  sections.push(`### 🟢 Standard Clauses (${standardRisks.length})`);
  if (standardRisks.length === 0) {
    sections.push('_No standard clauses identified._');
  } else {
    for (const c of standardRisks) {
      sections.push(`#### ${c.title}`);
      sections.push(`**Plain-English Meaning:** ${c.simplified}`);
      sections.push('');
    }
  }

  sections.push('## Actionable Checklist');
  const immediate = data.checklist.filter((i) => i.timing === 'immediate');
  const beforeSigning = data.checklist.filter((i) => i.timing === 'before_signing');
  const afterSigning = data.checklist.filter((i) => i.timing === 'after_signing');

  sections.push('### Immediate Actions');
  if (immediate.length === 0) sections.push('_None_');
  for (const item of immediate) {
    sections.push(`- [ ] **[${item.actionType.toUpperCase()}]** ${item.description}`);
  }
  sections.push('');

  sections.push('### Before Signing');
  if (beforeSigning.length === 0) sections.push('_None_');
  for (const item of beforeSigning) {
    sections.push(`- [ ] **[${item.actionType.toUpperCase()}]** ${item.description}`);
  }
  sections.push('');

  sections.push('### After Signing');
  if (afterSigning.length === 0) sections.push('_None_');
  for (const item of afterSigning) {
    sections.push(`- [ ] **[${item.actionType.toUpperCase()}]** ${item.description}`);
  }
  sections.push('');

  sections.push('## Questions for Your Legal Counsel');
  if (data.lawyerQuestions?.length) {
    data.lawyerQuestions.forEach((q, idx) => {
      sections.push(`${idx + 1}. **${q.question}**`);
      sections.push(`   _Context:_ ${q.context}`);
      sections.push('');
    });
  } else {
    sections.push('_No specific lawyer questions generated._');
  }

  return sections.join('\n');
}

export function formatDocumentPlainText(data: DocumentAnalysis, fileName?: string): string {
  const sections: string[] = [STATUTORY_DISCLAIMER_HEADER, ''];

  sections.push(`DOCUMENT ANALYSIS REPORT: ${data.documentType.toUpperCase()}`);
  if (fileName) sections.push(`Original File: ${fileName}`);
  sections.push(`Identified Parties: ${data.parties?.join(', ') || 'Not specified'}`);
  sections.push('==========================================================================');
  sections.push('');

  sections.push('EXECUTIVE SUMMARY:');
  sections.push(data.summary);
  sections.push('');

  sections.push('RISK SCORECARD:');
  sections.push('--------------------------------------------------------------------------');
  for (const c of data.clauses) {
    sections.push(`[${c.risk.toUpperCase()}] ${c.title} (Obligation: ${c.obligation})`);
    sections.push(`Reason: ${c.riskReason}`);
    sections.push(`Plain-English: ${c.simplified}`);
    sections.push(`Original Excerpt: "${c.originalText.trim()}"`);
    sections.push('');
  }

  sections.push('ACTIONABLE CHECKLIST:');
  sections.push('--------------------------------------------------------------------------');
  for (const item of data.checklist) {
    sections.push(`[ ] (${item.timing.toUpperCase()} / ${item.actionType.toUpperCase()}) ${item.description}`);
  }
  sections.push('');

  sections.push('QUESTIONS FOR YOUR LEGAL COUNSEL:');
  sections.push('--------------------------------------------------------------------------');
  data.lawyerQuestions.forEach((q, idx) => {
    sections.push(`${idx + 1}. ${q.question}`);
    sections.push(`   Context: ${q.context}`);
  });

  return sections.join('\n');
}

// ==========================================
// Mode 2: Situation Navigator Formatters
// ==========================================

export function formatSituationMarkdown(data: SituationAnalysis, description?: string): string {
  const sections: string[] = [STATUTORY_DISCLAIMER_HEADER, ''];

  sections.push(`# Situation Navigation Dossier: ${data.disputeCategory.toUpperCase()}`);
  sections.push(`**Estimated Resolution Timeline:** ${data.estimatedTimeline}`);
  sections.push('');

  if (data.deadlineFlags?.length > 0) {
    sections.push('> ⚠️ **TIME-SENSITIVE DEADLINE WARNINGS:**');
    for (const flag of data.deadlineFlags) {
      sections.push(`> - ${flag}`);
    }
    sections.push('');
  }

  if (description) {
    sections.push('## User Situation Background');
    sections.push(description);
    sections.push('');
  }

  sections.push('## Situation Analysis & Overview');
  sections.push(data.summary);
  sections.push('');

  sections.push('## Your Statutory Rights & Protections');
  for (const right of data.rights) {
    sections.push(`### ${right.title}`);
    sections.push(right.explanation);
    sections.push(`*Statute / Doctrine Reference:* \`${right.statuteReference}\``);
    sections.push('');
  }

  sections.push('## Procedural Next Steps Roadmap');
  for (const step of data.roadmap) {
    const doableTag = step.doableWithoutLawyer ? '🟢 (Doable without attorney)' : '🔴 (Attorney recommended)';
    sections.push(`### [${step.urgency.toUpperCase()}] ${step.step} ${doableTag}`);
    sections.push(step.description);
    sections.push('');
  }

  sections.push('## Documents & Evidence to Gather');
  for (const doc of data.documentsToGather) {
    sections.push(`- [ ] **${doc.document}**`);
    sections.push(`  *Why needed:* ${doc.why}`);
  }
  sections.push('');

  sections.push('## When to Consult Licensed Legal Counsel');
  for (const trigger of data.whenToCallLawyer) {
    sections.push(`- ${trigger}`);
  }

  return sections.join('\n');
}

export function formatSituationPlainText(data: SituationAnalysis, description?: string): string {
  const sections: string[] = [STATUTORY_DISCLAIMER_HEADER, ''];

  sections.push(`SITUATION NAVIGATION DOSSIER: ${data.disputeCategory.toUpperCase()}`);
  sections.push(`Estimated Timeline: ${data.estimatedTimeline}`);
  sections.push('==========================================================================');
  sections.push('');

  if (data.deadlineFlags?.length > 0) {
    sections.push('!!! URGENT DEADLINES / STATUTE OF LIMITATIONS !!!');
    for (const flag of data.deadlineFlags) {
      sections.push(`* ${flag}`);
    }
    sections.push('');
  }

  if (description) {
    sections.push('USER SITUATION:');
    sections.push(description);
    sections.push('');
  }

  sections.push('OVERVIEW:');
  sections.push(data.summary);
  sections.push('');

  sections.push('STATUTORY RIGHTS:');
  sections.push('--------------------------------------------------------------------------');
  for (const right of data.rights) {
    sections.push(`* ${right.title}`);
    sections.push(`  ${right.explanation}`);
    sections.push(`  Citation: ${right.statuteReference}`);
    sections.push('');
  }

  sections.push('NEXT STEPS ROADMAP:');
  sections.push('--------------------------------------------------------------------------');
  for (const step of data.roadmap) {
    const doable = step.doableWithoutLawyer ? '[Self-Representable]' : '[Lawyer Recommended]';
    sections.push(`(${step.urgency.toUpperCase()}) ${step.step} ${doable}`);
    sections.push(`  ${step.description}`);
    sections.push('');
  }

  sections.push('DOCUMENTS & EVIDENCE TO GATHER:');
  sections.push('--------------------------------------------------------------------------');
  for (const doc of data.documentsToGather) {
    sections.push(`[ ] ${doc.document} - ${doc.why}`);
  }
  sections.push('');

  sections.push('WHEN TO CALL A LAWYER:');
  sections.push('--------------------------------------------------------------------------');
  for (const trigger of data.whenToCallLawyer) {
    sections.push(`* ${trigger}`);
  }

  return sections.join('\n');
}

// ==========================================
// Mode 3: Document Comparison Formatters
// ==========================================

export function formatComparisonMarkdown(data: Comparison, labelA?: string, labelB?: string): string {
  const nameA = labelA || 'Document A';
  const nameB = labelB || 'Document B';
  const sections: string[] = [STATUTORY_DISCLAIMER_HEADER, ''];

  sections.push(`# Document Comparison Dossier: ${nameA} vs ${nameB}`);
  sections.push(`**Overall Favorability:** ${data.favorabilityVerdict.toUpperCase()}`);
  sections.push(`**Verdict Rationale:** ${data.verdictRationale}`);
  sections.push('');

  sections.push('## Comparative Metrics');
  sections.push(`- Clauses Favoring ${nameA}: ${data.favorabilityMetrics.clausesFavoringDocA}`);
  sections.push(`- Clauses Favoring ${nameB}: ${data.favorabilityMetrics.clausesFavoringDocB}`);
  sections.push(`- Critical Inconsistencies: ${data.favorabilityMetrics.criticalInconsistencies}`);
  sections.push('');

  if (data.inconsistencies?.length > 0) {
    sections.push('## Inconsistencies & Contradictions');
    for (const inc of data.inconsistencies) {
      sections.push(`### [${inc.severity.toUpperCase()}] ${inc.clauseTitle}`);
      sections.push(inc.description);
      sections.push('');
    }
  }

  sections.push('## Side-by-Side Differences');
  for (const diff of data.clauseDifferences) {
    const favorLabel = diff.favors === 'docA' ? nameA : diff.favors === 'docB' ? nameB : 'Neutral';
    sections.push(`### ${diff.category} (Risk: ${diff.riskRating.toUpperCase()} | Favors: ${favorLabel})`);
    sections.push(`**Analysis:** ${diff.notes}`);
    sections.push(`**${nameA}:**`);
    sections.push('```');
    sections.push(diff.textDocA);
    sections.push('```');
    sections.push(`**${nameB}:**`);
    sections.push('```');
    sections.push(diff.textDocB);
    sections.push('```');
    sections.push('');
  }

  sections.push('## Negotiation Guide');
  sections.push(`**Overall Recommendation:** ${data.negotiationGuide.recommendation}`);
  sections.push('');

  sections.push('### Push Back On');
  if (data.negotiationGuide.pushBack.length === 0) sections.push('_None_');
  for (const item of data.negotiationGuide.pushBack) {
    sections.push(`#### ${item.clauseTitle}`);
    sections.push(`*Rationale:* ${item.rationale}`);
    if (item.suggestedAlternative) {
      sections.push(`*Suggested Alternative:* "${item.suggestedAlternative}"`);
    }
    sections.push('');
  }

  sections.push('### Accept As-Is');
  if (data.negotiationGuide.acceptAsIs.length === 0) sections.push('_None_');
  for (const item of data.negotiationGuide.acceptAsIs) {
    sections.push(`#### ${item.clauseTitle}`);
    sections.push(`*Rationale:* ${item.rationale}`);
    sections.push('');
  }

  sections.push('### Flag for Lawyer Review');
  if (data.negotiationGuide.flagForLawyer.length === 0) sections.push('_None_');
  for (const item of data.negotiationGuide.flagForLawyer) {
    sections.push(`#### ${item.clauseTitle}`);
    sections.push(`*Rationale:* ${item.rationale}`);
    if (item.suggestedAlternative) {
      sections.push(`*Suggested Counter-Language:* "${item.suggestedAlternative}"`);
    }
    sections.push('');
  }

  return sections.join('\n');
}

export function formatComparisonPlainText(data: Comparison, labelA?: string, labelB?: string): string {
  const nameA = labelA || 'Document A';
  const nameB = labelB || 'Document B';
  const sections: string[] = [STATUTORY_DISCLAIMER_HEADER, ''];

  sections.push(`DOCUMENT COMPARISON DOSSIER: ${nameA.toUpperCase()} VS ${nameB.toUpperCase()}`);
  sections.push(`Overall Verdict: ${data.favorabilityVerdict.toUpperCase()}`);
  sections.push(`Verdict Rationale: ${data.verdictRationale}`);
  sections.push('==========================================================================');
  sections.push('');

  sections.push('METRICS:');
  sections.push(`* Favoring ${nameA}: ${data.favorabilityMetrics.clausesFavoringDocA}`);
  sections.push(`* Favoring ${nameB}: ${data.favorabilityMetrics.clausesFavoringDocB}`);
  sections.push(`* Critical Inconsistencies: ${data.favorabilityMetrics.criticalInconsistencies}`);
  sections.push('');

  if (data.inconsistencies?.length > 0) {
    sections.push('INCONSISTENCIES:');
    sections.push('--------------------------------------------------------------------------');
    for (const inc of data.inconsistencies) {
      sections.push(`[${inc.severity.toUpperCase()}] ${inc.clauseTitle}: ${inc.description}`);
    }
    sections.push('');
  }

  sections.push('DIFFERENCES:');
  sections.push('--------------------------------------------------------------------------');
  for (const diff of data.clauseDifferences) {
    const favorLabel = diff.favors === 'docA' ? nameA : diff.favors === 'docB' ? nameB : 'Neutral';
    sections.push(`[${diff.category}] Risk: ${diff.riskRating.toUpperCase()} | Favors: ${favorLabel}`);
    sections.push(`Notes: ${diff.notes}`);
    sections.push(`${nameA}: "${diff.textDocA.trim()}"`);
    sections.push(`${nameB}: "${diff.textDocB.trim()}"`);
    sections.push('');
  }

  sections.push('NEGOTIATION GUIDE:');
  sections.push('--------------------------------------------------------------------------');
  sections.push(`Strategy: ${data.negotiationGuide.recommendation}`);
  sections.push('');
  sections.push('Push Back:');
  data.negotiationGuide.pushBack.forEach((item) => {
    sections.push(`- ${item.clauseTitle}: ${item.rationale}`);
  });
  sections.push('');
  sections.push('Accept As-Is:');
  data.negotiationGuide.acceptAsIs.forEach((item) => {
    sections.push(`- ${item.clauseTitle}: ${item.rationale}`);
  });
  sections.push('');
  sections.push('Flag for Lawyer:');
  data.negotiationGuide.flagForLawyer.forEach((item) => {
    sections.push(`- ${item.clauseTitle}: ${item.rationale}`);
  });

  return sections.join('\n');
}
